from enum import Enum


class ServerEventType(Enum):
    CREATE_PLAYER_REQUEST = 0
    PLAYER_READY = 1
    START_GAME = 2
    PLAYER_MOVED = 3
    ADD_DOT = 4
    SERVER_DISCONNECT = 5
    CLIENT_CONNECTION_CLOSED = 6
    CLIENT_EXIT = 7
    STOP_SERVER_EVENTS = 7
